name: angular_dart
description: A web app that uses AngularDart Components
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.1.0'

dependencies:
  ngdart: ^8.0.0-dev.2
  ngcomponents: ^3.0.0-dev.1

dev_dependencies:
  ngtest: ^5.0.0-dev.1
  build_runner: ^2.2.0
  build_version: ^2.1.1
  build_test: ^2.1.5
  build_web_compilers: ^3.2.4
  lints: ^2.1.0
  test: ^1.21.0
